### ISSUE TITLE
Feature: retain Javadoc of previous releases 

### ISSUE THREAD

**Issue by UnaiUribarri-TomTom** [actions/deploy-pages#114]
I have a repository that uploads Javadoc of each release as gh-pages. The problem is that every time a new version is published, the Javadoc of the previous releases of my library is lost.

Is there any way to retain the Javadoc of previous releases?

Thank you!

**Comment by JamesMGreene** [comment]
My initial reaction is that this seems like it probably is not related to this deployment action. If you can provide more details on your configuration, a link to a public/example repo, etc., then we may be able to offer you a suggestion.

Otherwise, you might want to try asking in a wider forum like the [GitHub community discussion boards](https://github.com/community/community/discussions).
