### ISSUE TITLE
Documentation Questions

### ISSUE THREAD

**Issue by mvs5465** [actions/deploy-pages#117]
Hi! We are beginning to use this and have some confusion. Would someone be able to help clarify a few items?

1. This seems to use [Github Environments](https://github.com/actions/deploy-pages/blame/main/README.md#L39) but Github Pages configuration references branches (`Your GitHub Pages site is currently being built from the /docs folder in the gh-pages branch.`). Is it expected to use branches, or environments?

2. There seems to be an implied dependency on [actions/upload-pages-artifact](https://github.com/actions/upload-pages-artifact). This upload-pages-artifact action assumes your code is in the `./_site` directory, but the `deploy-pages` action seems to assume your code is in `./docs`. Is this true? I had to hardcode either one or the other so they were both the same?

3. Is the expected output of this job a new commit to the `gh-pages` branch?

**Comment by JamesMGreene** [comment]
> 1. This seems to use [Github Environments](https://github.com/actions/deploy-pages/blame/main/README.md#L39) but Github Pages configuration references branches (Your GitHub Pages site is currently being built from the /docs folder in the gh-pages branch.). Is it expected to use branches, or environments?

You are describing a repository that is configured to deploy to Pages using a [branch publishing configuration](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch), which is the long-standing but still fully supported legacy approach. If this is the approach you want, then you should NOT be using/creating custom Actions workflows using this Action in order to deploy your Pages site; GitHub will simply take care of it on your behalf whenever you push a new commit.

If you are attempting to utilize this Action directly for deploying your Pages site, however, you need to configure your repository to deploy to Pages using a [custom Actions workflow publishing configuration](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow).

When you switch to using the custom Actions workflow configuration, you should then see suggestions in the UI for Pages starter workflows that may be relevant to your repository's contents. Alternatively, you can find the source templates (read: not 100% usable without a few changes) for those suggested Pages starter workflows in this repository: https://github.com/actions/starter-workflows/tree/main/pages

> There seems to be an implied dependency on [actions/upload-pages-artifact](https://github.com/actions/upload-pages-artifact). This upload-pages-artifact action assumes your code is in the ./_site directory, but the deploy-pages action seems to assume your code is in ./docs. Is this true? I had to hardcode either one or the other so they were both the same?

:warning: The following answer is only relevant if you have chosen to move ahead with using a custom Actions workflow for publishing instead of the branch-based model.

Using `actions/upload-pages-artifact` isn't a strict requirement, though it is the approach we recommend. If you do, you can also [specify a custom path](https://github.com/actions/upload-pages-artifact/blob/main/action.yml#L9-L12) to utilize, e.g.:

```yaml
# within your Actions workflow build job's steps...

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
```

> 3. Is the expected output of this job a new commit to the gh-pages branch?

No, the deployment uses a transient Actions artifact (e.g. created by the `actions/upload-pages-artifact` Action, or similar). As such, it does not push any commits to your repository regardless of if you already have `gh-pages` branch present.

---

But yes, you are right that we could improve our documentation here to clarify some of these concepts. 😊

**Comment by mvs5465** [comment]
Thanks @JamesMGreene! That clarified a ton, and I'm realizing our Github Enterprise doesn't have the option to deploy using Github Actions yet. Appreciate the answer, whenever this makes its way to enterprise I will try it out!
