### ISSUE TITLE
GitHub Pages needs to be enabled in settings (not just an environment named github-pages)

### ISSUE THREAD

**Issue by anthonyronda** [actions/deploy-pages#21]
I tried getting this working for longer than I would like to admit before I discovered this was why it was failing.

When GitHub Pages isn't enabled, the telemetry for this action also fails to emit.

I would prefer if the usual GitHub pages rebuild on push doesn't happen, but I can certainly make do while it is in beta (and thank you for developing the beta in public).

**Comment by yoannchaudet** [comment]
Hello,

This is the current expected behavior. Today Pages is driven by branches. You can enable Pages by pushing a `gh-pages` branch to your repository (or explicitly enabling the feature in the settings of your repo or via API).

With the work we are currently starting around allowing workflow customization, creating/deleting a `github-pages` environment will become the new way to enable/disable Pages ;)

**Comment by anthonyronda** [comment]
Indeed it makes sense that this would be temporary. Thanks

**Comment by anthonyronda** [comment]
In order to avoid two workflows triggered on a push, I'm able to disable pages-build-deployment from the Actions tab and my workflow still works (for the other folks who come across this)
