### ISSUE TITLE
Unable to link to image from README.md

### ISSUE THREAD

**Issue by davidgammon-mettle** [actions/deploy-pages#238]
I've not been able to link to an image that was deployed using the deploy pages action. I've tried various urls such as `https://xxxx.github.io/my-repo/jmy-img.png` with no luck. I'm getting this response from Camo:
`Non-Image content-type returned`

I'm guessing this is down to Camo not being able to access Github Pages because the Pages it is trying to access is private. 

Should the deployed Pages be accessible in the README.md?

**Comment by JamesMGreene** [comment]
Your guess is correct, I'm afraid.

Accessing Private Pages sites always require active user authentication, so it's going to redirect from the image URL to an Pages authentication URL.

Letting a README (or other Markdown file) from a different repo would open a security vulnerability, particularly since Camo globally caches them for quicker display.
