### ISSUE TITLE
Unable to deploy, task marked as completed but the artifact is not uploaded

### ISSUE THREAD

**Issue by stefanobartoletti** [actions/deploy-pages#259]
I'm having some problems to successfully execute this action.

My configuration is here:

https://github.com/stefanobartoletti/nuxt-social-share/blob/main/.github/workflows/gh-pages.yml

While the logs of the latest run are here:

https://github.com/stefanobartoletti/nuxt-social-share/actions/runs/6950250226

The `deploy` task is marked as completed, but the page at https://stefanobartoletti.github.io/nuxt-social-share/ is only blank HTML.

As you can see the artifact is built and contains the generated static website.

---

The "artifact exchange URL" inside the task gives the following value

https://pipelinesghubeus15.actions.githubusercontent.com/uNFUc1trwFENsFwkzlcZRcupmsMp7zFHyNPynsejKcILFyT7eQ/_apis/pipelines/workflows/6950250226/artifacts?api-version=6.0-preview

which has the following content:

`{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}`

This seems to be related somehow to #236, in that case the problem seemed to be some non-ASCII character in the branch name, a condition that doesn't apply in my case (the branch is `main`)

**Comment by JamesMGreene** [comment]
Despite the page appearing blank, I definitely see Nuxt content when I view the source of the page:

```html
<!DOCTYPE html>
<html >
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/_nuxt/entry.b58322c9.css">
<link rel="modulepreload" as="script" crossorigin href="/_nuxt/entry.fd52b42d.js">
<link rel="prefetch" as="style" href="/_nuxt/error-404.1b80d82b.css">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-404.cc5a933f.js">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/_plugin-vue_export-helper.e03c7cdd.js">
<link rel="prefetch" as="style" href="/_nuxt/error-500.331c2e95.css">
<link rel="prefetch" as="script" crossorigin href="/_nuxt/error-500.eddd9705.js">
<script type="module" src="/_nuxt/entry.fd52b42d.js" crossorigin></script></head>
<body ><div id="__nuxt"></div><script type="application/json" id="__NUXT_DATA__" data-ssr="false">[{"_errors":1,"serverRendered":2,"data":3,"state":4},{},false,{},{}]</script>
<script>window.__NUXT__={};window.__NUXT__.config={public:{socialShare:{styled:false,label:true}},app:{baseURL:"/",buildAssetsDir:"/_nuxt/",cdnURL:""}}</script></body>
</html>
```

Looks like your URL pathing is incorrect. Because your URLs begin with `/`, they are seeking out files at `https://stefanobartoletti.github.io/...` rather than `https://stefanobartoletti.github.io/nuxt-social-share/...`.

You likely need to revise your build process to incorporate the destination domain in as your Nuxt base URL.

You can utilize the [`actions/configure-pages`](https://github.com/actions/configure-pages) action in your deployment workflow to get the relevant values. The action has preset for Nuxt, but I believe it only works with Nuxt v2.

The basic idea is you'll want to [build your Nuxt app for static hosting](https://nuxt.com/docs/getting-started/deployment#static-hosting) and then ensure your base URL correctly includes your project repo's path.

In Nuxt v2, that meant [adding a router base path to the configuration file](https://v2.nuxt.com/deployments/github-pages#deploying-to-github-pages-for-repository). I'm not familiar enough to Nuxt v3 to be sure, but it looks like you may need to [set `app.baseURL` in your configuration](https://nuxt.com/docs/api/nuxt-config#baseurl).

A minimal workaround for this would probably be to add something like the following 2 steps between your checkout and build steps:

```yaml
      - uses: actions/configure-pages@v3
        id: pages
      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ssr: false,"
          replace: "ssr: false, app: { baseURL: '${{ steps.pages.outputs.base_path}}/' }},"
          regex: false
          include: "playground/nuxt.config.ts"
```

**Comment by stefanobartoletti** [comment]
Thanks!
