### ISSUE TITLE
When the preview feature will be available

### ISSUE THREAD

**Issue by sunny0826** [actions/deploy-pages#337]
I've observed that the preview feature is already active on the jekyll-preview.yml workflow at https://github.com/github/opensource.guide/blob/main/.github/workflows/jekyll-preview.yml. However, the [README documentation](https://github.com/actions/deploy-pages?tab=readme-ov-file#inputs-) still indicates that this feature is not publicly available. Given that I've seen some third-party Actions have implemented this capability, I'm inquiring about the timeline for when this feature will be officially rolled out for general use.

**Comment by AlekSi** [comment]
See also https://github.com/orgs/community/discussions/7730

**Comment by patrickelectric** [comment]
Just to add on that, I did try a couple of attempts with the help of a friend to trigger the event through a PR, you can check the action here: https://github.com/patrickelectric/cockpit-public/actions/runs/9893087461

As you can see, the action is running with the same configuration as available in the opensource.guide repository.
Added the steps manually:
https://github.com/patrickelectric/cockpit-public/blob/master/.github/workflows/ci.yml#L70-L87
and also using a standalone action:
https://github.com/patrickelectric/cockpit-public/blob/master/.github/workflows/deploy-page.yml

On both attempts I was able to have the action to deploy the page, but not to drafts.github.io but to my own github pages: 
![image](https://github.com/actions/deploy-pages/assets/1215497/11579883-cbb6-4cdf-b455-6328230bf06c)


:warning: I know that this is not public and in alpha phase, but it would be nice to know if this feature is limited to a couple of repositories, or available but not documented at all. Because I put a lot of time investigating this feature and would like to know :rofl:

**Comment by danielorbach** [comment]
Previously the GitHub team closed https://github.com/actions/deploy-pages/issues/180 without any timeline. Hope they provide more information this time around.

**Comment by neongreen** [comment]
https://github.com/emilk/egui/pull/5131 is a nice example of how this could be done with existing GitHub actions, while we're waiting for the official feature

**Comment by yoannchaudet** [comment]
No ETA at the moment.

**Comment by ImLunaHey** [comment]
@yoannchaudet if there's no ETA why close this?

**Comment by landsman** [comment]
Please make it possible
